window.ART_DATA_1 = [
  // ===== Category 1: Nature (10 pieces) =====
  { id: 'sunset', title: 'Sunset Scene', category: 'Nature', html: '<div class="sunset"><div class="water"></div></div>' },
  { id: 'aurora', title: 'Aurora Borealis', category: 'Nature', html: '<div class="aurora"></div>' },
  { id: 'rainbow', title: 'Rainbow Arc', category: 'Nature', html: '<div class="rainbow"></div>' },
  { id: 'cloud', title: 'Fluffy Cloud', category: 'Nature', html: '<div class="cloud"></div>' },
  { id: 'snowflake', title: 'Snowflake Crystal', category: 'Nature', html: '<div class="snowflake"></div>' },
  { id: 'raindrop', title: 'Raindrop', category: 'Nature', html: '<div class="raindrop"></div>' },
  { id: 'wave', title: 'Ocean Wave', category: 'Nature', html: '<div class="wave"></div>' },
  { id: 'tornado', title: 'Tornado', category: 'Nature', html: '<div class="tornado"></div>' },
  { id: 'lightning', title: 'Lightning Bolt', category: 'Nature', html: '<div class="lightning"></div>' },
  { id: 'volcano', title: 'Volcano', category: 'Nature', html: '<div class="volcano"></div>' },

  // ===== Category 2: Animals (10 pieces) =====
  { id: 'cat', title: 'Cat', category: 'Animals', html: '<div class="cat"><div class="head"></div><div class="ear-left"></div><div class="ear-right"></div><div class="eye-left"></div><div class="eye-right"></div><div class="nose"></div><div class="mouth"></div><div class="whisker"></div><div class="whisker"></div><div class="whisker"></div><div class="whisker"></div></div>' },
  { id: 'dog', title: 'Dog', category: 'Animals', html: '<div class="dog"><div class="head"></div><div class="ear-left"></div><div class="ear-right"></div><div class="eye-left"></div><div class="eye-right"></div><div class="nose"></div><div class="mouth"></div></div>' },
  { id: 'penguin', title: 'Penguin', category: 'Animals', html: '<div class="penguin"><div class="head"></div><div class="eye-left"></div><div class="eye-right"></div><div class="body"></div></div>' },
  { id: 'owl', title: 'Owl', category: 'Animals', html: '<div class="owl"><div class="head"></div><div class="eye-left"></div><div class="eye-right"></div><div class="nose"></div></div>' },
  { id: 'fish', title: 'Fish', category: 'Animals', html: '<div class="fish"><div class="head"></div><div class="body"></div></div>' },
  { id: 'butterfly', title: 'Butterfly', category: 'Animals', html: '<div class="butterfly"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },
  { id: 'ladybug', title: 'Ladybug', category: 'Animals', html: '<div class="ladybug"><div class="head"></div><div class="eye-left"></div><div class="eye-right"></div><div class="nose"></div></div>' },
  { id: 'whale', title: 'Whale', category: 'Animals', html: '<div class="whale"><div class="head"></div><div class="eye-left"></div><div class="body"></div></div>' },
  { id: 'flamingo', title: 'Flamingo', category: 'Animals', html: '<div class="flamingo"><div class="head"></div><div class="body"></div></div>' },
  { id: 'octopus', title: 'Octopus', category: 'Animals', html: '<div class="octopus"><div class="eye-left"></div><div class="eye-right"></div><div class="head"></div><div class="body"></div></div>' },

  // ===== Category 3: Food & Drink (10 pieces) =====
  { id: 'coffee', title: 'Coffee Cup', category: 'Food & Drink', html: '<div class="coffee"><div class="liquid"></div><div class="steam"><span></span><span></span><span></span></div></div>' },
  { id: 'pizza', title: 'Pizza Slice', category: 'Food & Drink', html: '<div class="pizza"><div class="head"></div><div class="body"></div></div>' },
  { id: 'donut', title: 'Donut', category: 'Food & Drink', html: '<div class="donut"><div class="head"></div></div>' },
  { id: 'icecream', title: 'Ice Cream Cone', category: 'Food & Drink', html: '<div class="icecream"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },
  { id: 'sushi', title: 'Sushi', category: 'Food & Drink', html: '<div class="sushi"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },
  { id: 'hamburger', title: 'Hamburger', category: 'Food & Drink', html: '<div class="hamburger"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },
  { id: 'cupcake', title: 'Cupcake', category: 'Food & Drink', html: '<div class="cupcake"><div class="head"></div><div class="body"></div></div>' },
  { id: 'wineglass', title: 'Wine Glass', category: 'Food & Drink', html: '<div class="wineglass"><div class="head"></div></div>' },
  { id: 'taco', title: 'Taco', category: 'Food & Drink', html: '<div class="taco"><div class="head"></div><div class="body"></div><div class="ear-left"></div></div>' },
  { id: 'popsicle', title: 'Popsicle', category: 'Food & Drink', html: '<div class="popsicle"><div class="head"></div></div>' },

  // ===== Category 4: Space (10 pieces) =====
  { id: 'rocket', title: 'Rocket Ship', category: 'Space', html: '<div class="rocket"><div class="body"></div><div class="window"></div><div class="fin-left"></div><div class="fin-right"></div><div class="flame"></div></div>' },
  { id: 'saturn', title: 'Saturn', category: 'Space', html: '<div class="saturn"><div class="head"></div></div>' },
  { id: 'ufo', title: 'UFO', category: 'Space', html: '<div class="ufo"><div class="head"></div><div class="body"></div></div>' },
  { id: 'astronaut', title: 'Astronaut', category: 'Space', html: '<div class="astronaut"><div class="body"></div><div class="head"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },
  { id: 'moonphases', title: 'Moon Phases', category: 'Space', html: '<div class="moonphases"><div class="head"></div></div>' },
  { id: 'satellite', title: 'Satellite', category: 'Space', html: '<div class="satellite"><div class="head"></div><div class="body"></div></div>' },
  { id: 'shootingstar', title: 'Shooting Star', category: 'Space', html: '<div class="shootingstar"></div>' },
  { id: 'blackhole', title: 'Black Hole', category: 'Space', html: '<div class="blackhole"><div class="head"></div></div>' },
  { id: 'spacestation', title: 'Space Station', category: 'Space', html: '<div class="spacestation"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },
  { id: 'alien', title: 'Alien', category: 'Space', html: '<div class="alien"><div class="eye-left"></div><div class="eye-right"></div><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },

  // ===== Category 5: Buildings (10 pieces) =====
  { id: 'house', title: 'House', category: 'Buildings', html: '<div class="house"><div class="roof"></div><div class="walls"></div><div class="door"></div><div class="window-left"></div><div class="window-right"></div><div class="chimney"></div><div class="chimney-smoke"><span></span><span></span><span></span></div></div>' },
  { id: 'skyscraper', title: 'Skyscraper', category: 'Buildings', html: '<div class="skyscraper"><div class="head"></div></div>' },
  { id: 'lighthouse', title: 'Lighthouse', category: 'Buildings', html: '<div class="lighthouse"><div class="head"></div><div class="body"></div></div>' },
  { id: 'castle', title: 'Castle', category: 'Buildings', html: '<div class="castle"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div><div class="nose"></div></div>' },
  { id: 'windmill', title: 'Windmill', category: 'Buildings', html: '<div class="windmill"><div class="head"></div><div class="body"></div></div>' },
  { id: 'igloo', title: 'Igloo', category: 'Buildings', html: '<div class="igloo"><div class="head"></div><div class="body"></div></div>' },
  { id: 'pagoda', title: 'Pagoda', category: 'Buildings', html: '<div class="pagoda"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div><div class="nose"></div></div>' },
  { id: 'tent', title: 'Tent', category: 'Buildings', html: '<div class="tent"><div class="head"></div><div class="body"></div><div class="ear-left"></div></div>' },
  { id: 'barn', title: 'Barn', category: 'Buildings', html: '<div class="barn"><div class="head"></div><div class="body"></div><div class="ear-left"></div></div>' },
  { id: 'church', title: 'Church', category: 'Buildings', html: '<div class="church"><div class="head"></div><div class="body"></div><div class="ear-left"></div><div class="ear-right"></div></div>' },

  // ===== Category 6: Vehicles (10 pieces) =====
  { id: 'vehicle-car', title: 'Car', category: 'Vehicles', html: '<div class="vehicle-car"><div class="wheel-left"></div><div class="wheel-right"></div><div class="window"></div><div class="window"></div><div class="window"></div><div class="headlight"></div></div>' },
  { id: 'vehicle-bicycle', title: 'Bicycle', category: 'Vehicles', html: '<div class="vehicle-bicycle"><div class="bike-wheel"></div><div class="bike-wheel"></div><div class="bike-frame"></div><div class="bike-seat"></div><div class="bike-pedal"></div></div>' },
  { id: 'vehicle-sailboat', title: 'Sailboat', category: 'Vehicles', html: '<div class="vehicle-sailboat"><div class="mast"></div><div class="sail"></div><div class="flag"></div></div>' },
  { id: 'vehicle-helicopter', title: 'Helicopter', category: 'Vehicles', html: '<div class="vehicle-helicopter"><div class="rotor"></div><div class="tail"></div><div class="skid"></div><div class="skid"></div><div class="skid"></div></div>' },
  { id: 'vehicle-balloon', title: 'Hot Air Balloon', category: 'Vehicles', html: '<div class="vehicle-balloon"><div class="rope"></div><div class="rope"></div><div class="rope"></div><div class="balloon-stripe"></div><div class="balloon-stripe"></div><div class="balloon-stripe"></div></div>' },
  { id: 'vehicle-submarine', title: 'Submarine', category: 'Vehicles', html: '<div class="vehicle-submarine"><div class="porthole"></div><div class="porthole"></div><div class="porthole"></div><div class="propeller"></div><div class="bubble"></div><div class="bubble"></div><div class="bubble"></div></div>' },
  { id: 'vehicle-train', title: 'Train', category: 'Vehicles', html: '<div class="vehicle-train"><div class="cabin"></div><div class="train-wheel"></div><div class="train-wheel"></div><div class="train-wheel"></div><div class="train-wheel"></div><div class="smoke"></div><div class="smoke"></div><div class="smoke"></div></div>' },
  { id: 'vehicle-bus', title: 'Bus', category: 'Vehicles', html: '<div class="vehicle-bus"><div class="bus-wheel"></div><div class="bus-wheel"></div><div class="bus-door"></div><div class="bus-sign"></div></div>' },
  { id: 'vehicle-scooter', title: 'Scooter', category: 'Vehicles', html: '<div class="vehicle-scooter"><div class="sc-wheel"></div><div class="sc-wheel"></div><div class="handlebar"></div><div class="footboard"></div></div>' },
  { id: 'vehicle-airplane', title: 'Airplane', category: 'Vehicles', html: '<div class="vehicle-airplane"><div class="wing"></div><div class="tail"></div><div class="engine"></div><div class="engine"></div></div>' },

  // ===== Category 7: Electronics (10 pieces) =====
  { id: 'elec-gamepad', title: 'Gamepad', category: 'Electronics', html: '<div class="elec-gamepad"><div class="dpad"></div><div class="grip-right"></div><div class="gp-btn"></div><div class="gp-btn"></div><div class="gp-btn"></div><div class="gp-btn"></div></div>' },
  { id: 'elec-camera', title: 'Camera', category: 'Electronics', html: '<div class="elec-camera"><div class="cam-lens"></div><div class="cam-flash"></div><div class="cam-btn"></div><div class="viewfinder"></div></div>' },
  { id: 'elec-laptop', title: 'Laptop', category: 'Electronics', html: '<div class="elec-laptop"><div class="keyboard"></div><div class="screen-line"></div><div class="screen-line"></div><div class="screen-line"></div><div class="screen-line"></div><div class="screen-line"></div></div>' },
  { id: 'elec-phone', title: 'Smartphone', category: 'Electronics', html: '<div class="elec-phone"><div class="notch"></div><div class="home-btn"></div><div class="notification"></div></div>' },
  { id: 'elec-tv', title: 'Retro TV', category: 'Electronics', html: '<div class="elec-tv"><div class="antenna"></div><div class="antenna"></div><div class="tv-knob"></div><div class="tv-knob"></div><div class="tv-leg"></div><div class="tv-leg"></div></div>' },
  { id: 'elec-mic', title: 'Microphone', category: 'Electronics', html: '<div class="elec-mic"><div class="mic-stand"></div><div class="sound-wave"></div><div class="sound-wave"></div></div>' },
  { id: 'elec-usb', title: 'USB Drive', category: 'Electronics', html: '<div class="elec-usb"><div class="usb-inner"></div><div class="usb-led"></div><div class="usb-symbol"></div></div>' },
  { id: 'elec-robot', title: 'Robot', category: 'Electronics', html: '<div class="elec-robot"><div class="robot-eye"></div><div class="robot-eye"></div><div class="robot-mouth"></div><div class="robot-neck"></div><div class="robot-body"></div><div class="robot-arm"></div><div class="robot-arm"></div></div>' },
  { id: 'elec-floppy', title: 'Floppy Disk', category: 'Electronics', html: '<div class="elec-floppy"><div class="floppy-slider"></div><div class="floppy-label"></div><div class="floppy-hole"></div></div>' },
  { id: 'elec-watch', title: 'Wristwatch', category: 'Electronics', html: '<div class="elec-watch"><div class="watch-face"><div class="hour-hand"></div><div class="minute-hand"></div><div class="second-hand"></div></div><div class="watch-marker"></div><div class="watch-marker"></div><div class="watch-marker"></div><div class="watch-marker"></div><div class="crown"></div></div>' },

  // ===== Category 8: Music (10 pieces) =====
  { id: 'music-vinyl', title: 'Vinyl Record', category: 'Music', html: '<div class="music-vinyl"><div class="vinyl-shine"></div></div>' },
  { id: 'music-headphones', title: 'Headphones', category: 'Music', html: '<div class="music-headphones"><div class="hp-cup"></div><div class="hp-cup"></div><div class="hp-note"></div><div class="hp-note"></div><div class="hp-note"></div></div>' },
  { id: 'music-piano', title: 'Piano Keys', category: 'Music', html: '<div class="music-piano"><div class="black-key"></div><div class="black-key"></div><div class="black-key"></div><div class="black-key"></div><div class="black-key"></div></div>' },
  { id: 'music-guitar', title: 'Guitar', category: 'Music', html: '<div class="music-guitar"><div class="guitar-neck"></div><div class="guitar-string"></div><div class="guitar-string"></div><div class="guitar-string"></div><div class="guitar-string"></div><div class="guitar-string"></div><div class="tuning-peg"></div><div class="tuning-peg"></div><div class="tuning-peg"></div><div class="tuning-peg"></div></div>' },
  { id: 'music-drums', title: 'Drum Kit', category: 'Music', html: '<div class="music-drums"><div class="snare"></div><div class="hihat"></div><div class="drumstick"></div><div class="drumstick"></div></div>' },
  { id: 'music-sax', title: 'Saxophone', category: 'Music', html: '<div class="music-sax"><div class="sax-mouthpiece"></div><div class="sax-key"></div><div class="sax-key"></div><div class="sax-key"></div><div class="sax-key"></div></div>' },
  { id: 'music-micstand', title: 'Mic Stand', category: 'Music', html: '<div class="music-micstand"><div class="ms-head"></div><div class="ms-spotlight"></div></div>' },
  { id: 'music-speaker', title: 'Speaker', category: 'Music', html: '<div class="music-speaker"><div class="woofer"></div><div class="tweeter"></div><div class="speaker-led"></div></div>' },
  { id: 'music-trumpet', title: 'Trumpet', category: 'Music', html: '<div class="music-trumpet"><div class="valve"></div><div class="valve"></div><div class="valve"></div><div class="mouthpiece"></div><div class="trumpet-note"></div><div class="trumpet-note"></div><div class="trumpet-note"></div></div>' },
  { id: 'music-harp', title: 'Harp', category: 'Music', html: '<div class="music-harp"><div class="harp-curve"></div><div class="harp-scroll"></div><div class="harp-string"></div><div class="harp-string"></div><div class="harp-string"></div><div class="harp-string"></div><div class="harp-string"></div><div class="harp-string"></div><div class="harp-string"></div><div class="harp-base"></div></div>' },

  // ===== Category 9: Emotions (10 pieces) =====
  { id: 'emo-heart', title: 'Heart', category: 'Emotions', html: '<div class="emo-heart"><div class="heart-shine"></div></div>' },
  { id: 'emo-happy', title: 'Happy Face', category: 'Emotions', html: '<div class="emo-happy"><div class="happy-eye"></div><div class="happy-eye"></div><div class="happy-mouth"></div><div class="happy-cheek"></div><div class="happy-cheek"></div></div>' },
  { id: 'emo-sad', title: 'Sad Face', category: 'Emotions', html: '<div class="emo-sad"><div class="sad-eye"></div><div class="sad-eye"></div><div class="sad-mouth"></div><div class="sad-tear"></div><div class="sad-tear"></div></div>' },
  { id: 'emo-angry', title: 'Angry Face', category: 'Emotions', html: '<div class="emo-angry"><div class="angry-eye"></div><div class="angry-eye"></div><div class="angry-brow"></div><div class="angry-brow"></div><div class="angry-mouth"></div></div>' },
  { id: 'emo-surprised', title: 'Surprised Face', category: 'Emotions', html: '<div class="emo-surprised"><div class="surprise-eye"></div><div class="surprise-eye"></div><div class="surprise-brow"></div><div class="surprise-brow"></div><div class="surprise-mouth"></div></div>' },
  { id: 'emo-cool', title: 'Cool Face', category: 'Emotions', html: '<div class="emo-cool"><div class="cool-glass"></div><div class="cool-glass"></div><div class="cool-bridge"></div><div class="cool-mouth"></div></div>' },
  { id: 'emo-wink', title: 'Wink Face', category: 'Emotions', html: '<div class="emo-wink"><div class="wink-eye-open"></div><div class="wink-eye-closed"></div><div class="wink-mouth"></div><div class="wink-tongue"></div></div>' },
  { id: 'emo-starry', title: 'Starry Eyes', category: 'Emotions', html: '<div class="emo-starry"><div class="star-eye"></div><div class="star-eye"></div><div class="starry-mouth"></div><div class="sparkle"></div><div class="sparkle"></div><div class="sparkle"></div></div>' },
  { id: 'emo-sleepy', title: 'Sleepy Face', category: 'Emotions', html: '<div class="emo-sleepy"><div class="sleepy-eye"></div><div class="sleepy-eye"></div><div class="sleepy-mouth"></div><div class="sleepy-z"></div><div class="sleepy-z"></div><div class="sleepy-z"></div></div>' },
  { id: 'emo-party', title: 'Party Face', category: 'Emotions', html: '<div class="emo-party"><div class="party-hat"></div><div class="party-eye"></div><div class="party-eye"></div><div class="party-mouth"></div><div class="party-horn"></div><div class="confetti"></div><div class="confetti"></div><div class="confetti"></div><div class="confetti"></div><div class="confetti"></div><div class="confetti"></div></div>' },

  // ===== Category 10: Weather (10 pieces) =====
  { id: 'weather-sun', title: 'Sun', category: 'Weather', html: '<div class="weather-sun"><div class="sun-face"></div></div>' },
  { id: 'weather-moon', title: 'Crescent Moon', category: 'Weather', html: '<div class="weather-moon"><div class="crater"></div><div class="crater"></div><div class="crater"></div><div class="moon-star"></div><div class="moon-star"></div><div class="moon-star"></div><div class="moon-star"></div><div class="moon-halo"></div></div>' },
  { id: 'weather-rain', title: 'Rain Cloud', category: 'Weather', html: '<div class="weather-rain"><div class="raindrop"></div><div class="raindrop"></div><div class="raindrop"></div><div class="raindrop"></div><div class="raindrop"></div><div class="raindrop"></div><div class="raindrop"></div><div class="lightning"></div></div>' },
  { id: 'weather-snowman', title: 'Snowman', category: 'Weather', html: '<div class="weather-snowman"><div class="snow-head"></div><div class="top-hat"></div><div class="carrot-nose"></div><div class="snow-eye"></div><div class="snow-eye"></div><div class="scarf"></div><div class="snow-arm"></div><div class="snow-arm"></div><div class="snowflake"></div><div class="snowflake"></div><div class="snowflake"></div></div>' },
  { id: 'weather-thermo', title: 'Thermometer', category: 'Weather', html: '<div class="weather-thermo"><div class="mercury"></div><div class="thermo-mark"></div><div class="thermo-mark"></div><div class="thermo-mark"></div><div class="thermo-mark"></div><div class="thermo-mark"></div></div>' },
  { id: 'weather-wind', title: 'Wind', category: 'Weather', html: '<div class="weather-wind"><div class="wind-line"></div><div class="wind-line"></div><div class="wind-line"></div><div class="wind-line"></div><div class="leaf"></div><div class="leaf"></div><div class="leaf"></div></div>' },
  { id: 'weather-fog', title: 'Fog', category: 'Weather', html: '<div class="weather-fog"><div class="fog-layer"></div><div class="fog-layer"></div><div class="fog-layer"></div><div class="fog-layer"></div><div class="fog-layer"></div><div class="fog-layer"></div></div>' },
  { id: 'weather-hail', title: 'Hailstorm', category: 'Weather', html: '<div class="weather-hail"><div class="hailstone"></div><div class="hailstone"></div><div class="hailstone"></div><div class="hailstone"></div><div class="hailstone"></div><div class="hailstone"></div><div class="impact"></div><div class="impact"></div></div>' },
  { id: 'weather-dew', title: 'Dew on Leaf', category: 'Weather', html: '<div class="weather-dew"><div class="vein"></div><div class="vein"></div><div class="vein"></div><div class="dewdrop"></div><div class="dewdrop"></div><div class="dewdrop"></div></div>' },
  { id: 'weather-vane', title: 'Weather Vane', category: 'Weather', html: '<div class="weather-vane"><div class="rooster"></div><div class="vane-dir">N</div><div class="vane-dir">S</div><div class="vane-dir">W</div><div class="vane-dir">E</div><div class="vane-ball"></div><div class="vane-arrows"></div></div>' }
];
