window.ART_DATA_2 = [
  // ===== Category 11: Shapes & Geometry (10 pieces) =====
  { id: 'geo-diamond', title: 'Diamond', category: 'Shapes & Geometry', html: '<div class="geo-diamond"><div class="diamond-sparkle s1"></div><div class="diamond-sparkle s2"></div><div class="diamond-sparkle s3"></div></div>' },
  { id: 'geo-hexagon', title: 'Hexagon', category: 'Shapes & Geometry', html: '<div class="geo-hexagon"></div>' },
  { id: 'geo-infinity', title: 'Infinity', category: 'Shapes & Geometry', html: '<div class="geo-infinity"></div>' },
  { id: 'geo-yinyang', title: 'Yin Yang', category: 'Shapes & Geometry', html: '<div class="geo-yinyang"><div class="yy-dot-light"></div><div class="yy-dot-dark"></div></div>' },
  { id: 'geo-celtic', title: 'Celtic Knot', category: 'Shapes & Geometry', html: '<div class="geo-celtic"><div class="celtic-ring"></div></div>' },
  { id: 'geo-sierpinski', title: 'Sierpinski Triangle', category: 'Shapes & Geometry', html: '<div class="geo-sierpinski"><div class="sier-tri-l"></div><div class="sier-tri-r"></div></div>' },
  { id: 'geo-illusion', title: 'Penrose Triangle', category: 'Shapes & Geometry', html: '<div class="geo-illusion"></div>' },
  { id: 'geo-cube', title: '3D Cube', category: 'Shapes & Geometry', html: '<div class="geo-cube"><div class="cube-top"></div></div>' },
  { id: 'geo-helix', title: 'DNA Helix', category: 'Shapes & Geometry', html: '<div class="geo-helix"><div class="helix-dot h1"></div><div class="helix-dot h2"></div><div class="helix-dot h3"></div><div class="helix-dot h4"></div><div class="helix-dot h5"></div><div class="helix-dot h6"></div><div class="helix-dot h7"></div><div class="helix-dot h8"></div><div class="helix-dot h9"></div><div class="helix-dot h10"></div><div class="helix-dot h11"></div><div class="helix-dot h12"></div><div class="helix-bar hb1"></div><div class="helix-bar hb2"></div><div class="helix-bar hb3"></div><div class="helix-bar hb4"></div><div class="helix-bar hb5"></div><div class="helix-bar hb6"></div></div>' },
  { id: 'geo-atom', title: 'Atom', category: 'Shapes & Geometry', html: '<div class="geo-atom"><div class="nucleus"></div><div class="orbit orbit-1"></div><div class="orbit orbit-2"></div><div class="orbit orbit-3"></div><div class="electron e1"></div><div class="electron e2"></div><div class="electron e3"></div></div>' },

  // ===== Category 12: Fantasy (10 pieces) =====
  { id: 'fan-ghost', title: 'Ghost', category: 'Fantasy', html: '<div class="fan-ghost"><div class="ghost-body"></div><div class="ghost-eye ghost-eye-l"></div><div class="ghost-eye ghost-eye-r"></div><div class="ghost-mouth"></div><div class="ghost-tail"></div></div>' },
  { id: 'fan-dragon', title: 'Dragon', category: 'Fantasy', html: '<div class="fan-dragon"><div class="horn-l"></div><div class="horn-r"></div><div class="dragon-eye"></div><div class="nostril"></div><div class="scale sc1"></div><div class="scale sc2"></div><div class="scale sc3"></div><div class="fire"></div></div>' },
  { id: 'fan-wizard', title: 'Wizard', category: 'Fantasy', html: '<div class="fan-wizard"><div class="hat-star"></div><div class="hat-star2"></div><div class="buckle"></div><div class="face"></div><div class="beard"></div></div>' },
  { id: 'fan-crystal', title: 'Crystal Ball', category: 'Fantasy', html: '<div class="fan-crystal"><div class="crystal-swirl"></div><div class="stand"></div></div>' },
  { id: 'fan-chest', title: 'Treasure Chest', category: 'Fantasy', html: '<div class="fan-chest"><div class="chest-body"></div><div class="chest-lid"></div><div class="band band-top"></div><div class="band band-mid"></div><div class="band band-bot"></div><div class="lock"></div><div class="gold g1"></div><div class="gold g2"></div><div class="gold g3"></div><div class="gold g4"></div><div class="gold g5"></div></div>' },
  { id: 'fan-wand', title: 'Magic Wand', category: 'Fantasy', html: '<div class="fan-wand"><div class="wand-star"></div><div class="sparkle sp1"></div><div class="sparkle sp2"></div><div class="sparkle sp3"></div></div>' },
  { id: 'fan-potion', title: 'Potion', category: 'Fantasy', html: '<div class="fan-potion"><div class="flask"><div class="liquid"></div></div><div class="neck"></div><div class="cork"></div><div class="bubble b1"></div><div class="bubble b2"></div><div class="bubble b3"></div></div>' },
  { id: 'fan-crown', title: 'Crown', category: 'Fantasy', html: '<div class="fan-crown"><div class="gem gem-top"></div><div class="gem gem-r"></div><div class="gem gem-g"></div><div class="gem gem-b"></div></div>' },
  { id: 'fan-sword', title: 'Sword', category: 'Fantasy', html: '<div class="fan-sword"><div class="blade"></div><div class="crossguard"></div><div class="grip"></div><div class="pommel"></div><div class="slash"></div></div>' },
  { id: 'fan-shield', title: 'Shield', category: 'Fantasy', html: '<div class="fan-shield"><div class="cross-v"></div><div class="cross-h"></div><div class="flash"></div></div>' },

  // ===== Category 13: Nature Plants (10 pieces) =====
  { id: 'plant-tree', title: 'Pine Tree', category: 'Nature Plants', html: '<div class="plant-tree"><div class="trunk"></div><div class="tier t1"></div><div class="tier t2"></div><div class="tier t3"></div><div class="tree-star"></div></div>' },
  { id: 'plant-rose', title: 'Rose', category: 'Nature Plants', html: '<div class="plant-rose"><div class="stem"></div><div class="petal p1"></div><div class="petal p2"></div><div class="petal p3"></div><div class="petal p4"></div><div class="center"></div><div class="leaf-l"></div><div class="leaf-r"></div></div>' },
  { id: 'plant-cactus', title: 'Cactus', category: 'Nature Plants', html: '<div class="plant-cactus"><div class="body"></div><div class="arm-l"></div><div class="arm-r"></div><div class="pot"></div><div class="needle n1"></div><div class="needle n2"></div><div class="needle n3"></div><div class="needle n4"></div><div class="needle n5"></div><div class="flower"></div></div>' },
  { id: 'plant-mushroom', title: 'Mushroom', category: 'Nature Plants', html: '<div class="plant-mushroom"><div class="cap"></div><div class="spot sp1"></div><div class="spot sp2"></div><div class="spot sp3"></div><div class="spot sp4"></div><div class="mush-stem"></div><div class="grass gr1"></div><div class="grass gr2"></div><div class="grass gr3"></div><div class="grass gr4"></div></div>' },
  { id: 'plant-leaf', title: 'Leaf', category: 'Nature Plants', html: '<div class="plant-leaf"><div class="vein v1"></div><div class="vein v2"></div><div class="vein v3"></div><div class="vein v4"></div></div>' },
  { id: 'plant-bonsai', title: 'Bonsai', category: 'Nature Plants', html: '<div class="plant-bonsai"><div class="pot"></div><div class="trunk"></div><div class="branch-l"></div><div class="branch-r"></div><div class="canopy c1"></div><div class="canopy c2"></div><div class="canopy c3"></div></div>' },
  { id: 'plant-bamboo', title: 'Bamboo', category: 'Nature Plants', html: '<div class="plant-bamboo"><div class="stalk s1"></div><div class="stalk s2"></div><div class="stalk s3"></div><div class="stalk s4"></div><div class="node nd1"></div><div class="node nd2"></div><div class="node nd3"></div><div class="bamboo-leaf bl1"></div><div class="bamboo-leaf bl2"></div><div class="bamboo-leaf bl3"></div><div class="bamboo-leaf bl4"></div></div>' },
  { id: 'plant-lotus', title: 'Lotus', category: 'Nature Plants', html: '<div class="plant-lotus"><div class="water"></div><div class="petal-outer po1"></div><div class="petal-outer po2"></div><div class="petal-outer po3"></div><div class="petal-outer po4"></div><div class="petal-outer po5"></div><div class="petal-inner pi1"></div><div class="petal-inner pi2"></div><div class="petal-inner pi3"></div><div class="lotus-center"></div></div>' },
  { id: 'plant-sunflower', title: 'Sunflower', category: 'Nature Plants', html: '<div class="plant-sunflower"><div class="sf-stem"></div><div class="sf-center"></div><div class="sf-petal sfp1"></div><div class="sf-petal sfp2"></div><div class="sf-petal sfp3"></div><div class="sf-petal sfp4"></div><div class="sf-petal sfp5"></div><div class="sf-petal sfp6"></div><div class="sf-petal sfp7"></div><div class="sf-petal sfp8"></div><div class="sf-petal sfp9"></div><div class="sf-petal sfp10"></div><div class="sf-petal sfp11"></div><div class="sf-petal sfp12"></div><div class="sf-leaf-l"></div><div class="sf-leaf-r"></div></div>' },
  { id: 'plant-acorn', title: 'Acorn', category: 'Nature Plants', html: '<div class="plant-acorn"><div class="acorn-cap"></div><div class="acorn-body"></div><div class="acorn-stem"></div></div>' },

  // ===== Category 14: Stationery (10 pieces) =====
  { id: 'stat-envelope', title: 'Envelope', category: 'Stationery', html: '<div class="stat-envelope"><div class="env-body"></div><div class="env-flap"></div><div class="env-seal"></div><div class="letter"></div></div>' },
  { id: 'stat-pencil', title: 'Pencil', category: 'Stationery', html: '<div class="stat-pencil"><div class="pencil-body"></div><div class="ferrule"></div><div class="eraser"></div><div class="tip"></div><div class="write-line"></div></div>' },
  { id: 'stat-book', title: 'Book', category: 'Stationery', html: '<div class="stat-book"><div class="spine"></div><div class="cover"></div><div class="pages"></div><div class="title-bar"></div></div>' },
  { id: 'stat-scissors', title: 'Scissors', category: 'Stationery', html: '<div class="stat-scissors"><div class="blade-l"></div><div class="blade-r"></div><div class="handle-l"></div><div class="handle-r"></div><div class="pivot"></div></div>' },
  { id: 'stat-clip', title: 'Paper Clip', category: 'Stationery', html: '<div class="stat-clip"></div>' },
  { id: 'stat-palette', title: 'Paint Palette', category: 'Stationery', html: '<div class="stat-palette"><div class="thumb-hole"></div><div class="paint pa1"></div><div class="paint pa2"></div><div class="paint pa3"></div><div class="paint pa4"></div><div class="paint pa5"></div><div class="paint pa6"></div><div class="brush"></div></div>' },
  { id: 'stat-stamp', title: 'Stamp', category: 'Stationery', html: '<div class="stat-stamp"><div class="stamp-body"></div><div class="stamp-art"></div><div class="perforation"></div><div class="postmark"></div></div>' },
  { id: 'stat-ruler', title: 'Ruler', category: 'Stationery', html: '<div class="stat-ruler"><div class="tick tick-major tm1"></div><div class="tick tick-major tm2"></div><div class="tick tick-major tm3"></div><div class="tick tick-major tm4"></div><div class="tick tick-major tm5"></div><div class="tick tick-major tm6"></div><div class="tick tick-major tm7"></div><div class="tick tick-major tm8"></div><div class="tick tick-major tm9"></div><div class="tick tick-major tm10"></div><div class="tick tick-minor tn1"></div><div class="tick tick-minor tn2"></div><div class="tick tick-minor tn3"></div><div class="tick tick-minor tn4"></div><div class="tick tick-minor tn5"></div><div class="tick tick-minor tn6"></div><div class="tick tick-minor tn7"></div><div class="tick tick-minor tn8"></div><div class="tick tick-minor tn9"></div></div>' },
  { id: 'stat-notepad', title: 'Notepad', category: 'Stationery', html: '<div class="stat-notepad"><div class="spiral"><div class="ring r1"></div><div class="ring r2"></div><div class="ring r3"></div><div class="ring r4"></div><div class="ring r5"></div><div class="ring r6"></div><div class="ring r7"></div><div class="ring r8"></div></div><div class="pad-page"></div><div class="pad-page-back"></div><div class="pad-page-back2"></div></div>' },
  { id: 'stat-ink', title: 'Ink Bottle', category: 'Stationery', html: '<div class="stat-ink"><div class="bottle"><div class="ink-liquid"></div></div><div class="neck"></div><div class="cap"></div><div class="ink-label"></div><div class="drip"></div></div>' },

  // ===== Category 15: Sports (10 pieces) =====
  { id: 'sport-basket', title: 'Basketball', category: 'Sports', html: '<div class="sport-basket"><div class="line-h"></div><div class="line-v"></div><div class="line-c1"></div><div class="line-c2"></div></div>' },
  { id: 'sport-soccer', title: 'Soccer Ball', category: 'Sports', html: '<div class="sport-soccer"><div class="pent pn1"></div><div class="pent pn2"></div><div class="pent pn3"></div><div class="pent pn4"></div><div class="pent pn5"></div></div>' },
  { id: 'sport-tennis', title: 'Tennis', category: 'Sports', html: '<div class="sport-tennis"><div class="racket-frame"></div><div class="racket-handle"></div><div class="racket-grid"></div><div class="ball"></div></div>' },
  { id: 'sport-trophy', title: 'Trophy', category: 'Sports', html: '<div class="sport-trophy"><div class="cup"></div><div class="handle-l"></div><div class="handle-r"></div><div class="stem"></div><div class="base"></div><div class="star"></div><div class="shine"></div></div>' },
  { id: 'sport-medal', title: 'Medal', category: 'Sports', html: '<div class="sport-medal"><div class="ribbon-l"></div><div class="ribbon-r"></div><div class="disc"></div><div class="medal-star"></div></div>' },
  { id: 'sport-bat', title: 'Baseball Bat', category: 'Sports', html: '<div class="sport-bat"><div class="bat-body"></div><div class="bat-ball"></div></div>' },
  { id: 'sport-football', title: 'Football', category: 'Sports', html: '<div class="sport-football"><div class="lace-line"></div><div class="lace la1"></div><div class="lace la2"></div><div class="lace la3"></div><div class="lace la4"></div><div class="lace la5"></div></div>' },
  { id: 'sport-boxing', title: 'Boxing Glove', category: 'Sports', html: '<div class="sport-boxing"><div class="glove"></div><div class="thumb"></div><div class="lacing"></div><div class="wrist"></div></div>' },
  { id: 'sport-bowling', title: 'Bowling', category: 'Sports', html: '<div class="sport-bowling"><div class="pin bp1"></div><div class="pin bp2"></div><div class="pin bp3"></div><div class="pin bp4"></div><div class="pin bp5"></div><div class="pin bp6"></div><div class="bowling-ball"></div></div>' },
  { id: 'sport-target', title: 'Target', category: 'Sports', html: '<div class="sport-target"><div class="ring ring-1"></div><div class="ring ring-2"></div><div class="ring ring-3"></div><div class="ring ring-4"></div><div class="ring bullseye"></div><div class="arrow-shaft"></div></div>' },

  // ===== Category 16: Symbols & Icons (10 pieces) =====
  { id: 'sym-power', title: 'Power Button', category: 'Symbols & Icons', html: '<div class="sym-power"></div>' },
  { id: 'sym-wifi', title: 'WiFi Signal', category: 'Symbols & Icons', html: '<div class="sym-wifi"><span></span><span></span></div>' },
  { id: 'sym-battery', title: 'Battery', category: 'Symbols & Icons', html: '<div class="sym-battery"><span></span><span></span><span></span></div>' },
  { id: 'sym-lock', title: 'Lock', category: 'Symbols & Icons', html: '<div class="sym-lock"><span></span></div>' },
  { id: 'sym-clock', title: 'Clock', category: 'Symbols & Icons', html: '<div class="sym-clock"><span></span><span></span><span></span></div>' },
  { id: 'sym-compass', title: 'Compass', category: 'Symbols & Icons', html: '<div class="sym-compass"><span></span><span></span></div>' },
  { id: 'sym-bell', title: 'Bell', category: 'Symbols & Icons', html: '<div class="sym-bell"><span></span><span></span></div>' },
  { id: 'sym-magnify', title: 'Magnifying Glass', category: 'Symbols & Icons', html: '<div class="sym-magnify"><span></span></div>' },
  { id: 'sym-gear', title: 'Gear', category: 'Symbols & Icons', html: '<div class="sym-gear"><span></span></div>' },
  { id: 'sym-qr', title: 'QR Code', category: 'Symbols & Icons', html: '<div class="sym-qr"><span></span></div>' },

  // ===== Category 17: Scenes (10 pieces) =====
  { id: 'scene-mountain', title: 'Mountain Night', category: 'Scenes', html: '<div class="scene-mountain"><span></span><span></span><span></span><span></span></div>' },
  { id: 'scene-city', title: 'City Skyline', category: 'Scenes', html: '<div class="scene-city"><span></span></div>' },
  { id: 'scene-beach', title: 'Beach', category: 'Scenes', html: '<div class="scene-beach"><span></span><span></span></div>' },
  { id: 'scene-underwater', title: 'Underwater', category: 'Scenes', html: '<div class="scene-underwater"><span></span><span></span><span></span></div>' },
  { id: 'scene-forest', title: 'Forest', category: 'Scenes', html: '<div class="scene-forest"><span></span><span></span><span></span></div>' },
  { id: 'scene-desert', title: 'Desert', category: 'Scenes', html: '<div class="scene-desert"><span></span><span></span><span></span></div>' },
  { id: 'scene-nightsky', title: 'Night Sky', category: 'Scenes', html: '<div class="scene-nightsky"><span></span></div>' },
  { id: 'scene-garden', title: 'Garden', category: 'Scenes', html: '<div class="scene-garden"><span></span><span></span><span></span></div>' },
  { id: 'scene-bridge', title: 'Bridge', category: 'Scenes', html: '<div class="scene-bridge"><span></span><span></span><span></span></div>' },
  { id: 'scene-waterfall', title: 'Waterfall', category: 'Scenes', html: '<div class="scene-waterfall"><span></span><span></span><span></span></div>' },

  // ===== Category 18: Characters (10 pieces) =====
  { id: 'char-ninja', title: 'Ninja', category: 'Characters', html: '<div class="char-ninja"><span></span><span></span><span></span><span></span></div>' },
  { id: 'char-pirate', title: 'Pirate', category: 'Characters', html: '<div class="char-pirate"><span></span><span></span><span></span><span></span></div>' },
  { id: 'char-king', title: 'King', category: 'Characters', html: '<div class="char-king"><span></span><span></span><span></span><span></span></div>' },
  { id: 'char-astro', title: 'Astronaut', category: 'Characters', html: '<div class="char-astro"><span></span><span></span></div>' },
  { id: 'char-hero', title: 'Superhero', category: 'Characters', html: '<div class="char-hero"><span></span><span></span><span></span></div>' },
  { id: 'char-viking', title: 'Viking', category: 'Characters', html: '<div class="char-viking"><span></span><span></span><span></span><span></span></div>' },
  { id: 'char-samurai', title: 'Samurai', category: 'Characters', html: '<div class="char-samurai"><span></span><span></span><span></span></div>' },
  { id: 'char-cowboy', title: 'Cowboy', category: 'Characters', html: '<div class="char-cowboy"><span></span><span></span><span></span><span></span></div>' },
  { id: 'char-detective', title: 'Detective', category: 'Characters', html: '<div class="char-detective"><span></span><span></span><span></span><span></span></div>' },
  { id: 'char-chef', title: 'Chef', category: 'Characters', html: '<div class="char-chef"><span></span><span></span><span></span><span></span><span></span></div>' },

  // ===== Category 19: Holidays (10 pieces) =====
  { id: 'hol-pumpkin', title: 'Pumpkin', category: 'Holidays', html: '<div class="hol-pumpkin"><span></span><span></span><span></span></div>' },
  { id: 'hol-xmastree', title: 'Christmas Tree', category: 'Holidays', html: '<div class="hol-xmastree"><span></span><span></span><span></span></div>' },
  { id: 'hol-gift', title: 'Gift Box', category: 'Holidays', html: '<div class="hol-gift"><span></span><span></span></div>' },
  { id: 'hol-fireworks', title: 'Fireworks', category: 'Holidays', html: '<div class="hol-fireworks"><span></span></div>' },
  { id: 'hol-snowglobe', title: 'Snow Globe', category: 'Holidays', html: '<div class="hol-snowglobe"><span></span><span></span></div>' },
  { id: 'hol-candy', title: 'Candy Cane', category: 'Holidays', html: '<div class="hol-candy"><span></span></div>' },
  { id: 'hol-egg', title: 'Easter Egg', category: 'Holidays', html: '<div class="hol-egg"><span></span></div>' },
  { id: 'hol-turkey', title: 'Turkey', category: 'Holidays', html: '<div class="hol-turkey"><span></span><span></span></div>' },
  { id: 'hol-clover', title: 'Four-Leaf Clover', category: 'Holidays', html: '<div class="hol-clover"><span></span><span></span><span></span></div>' },
  { id: 'hol-cake', title: 'Birthday Cake', category: 'Holidays', html: '<div class="hol-cake"><span></span><span></span><span></span></div>' },

  // ===== Category 20: Abstract (10 pieces) =====
  { id: 'abs-orb', title: 'Orb', category: 'Abstract', html: '<div class="abs-orb"><span></span></div>' },
  { id: 'abs-ring', title: 'Rainbow Ring', category: 'Abstract', html: '<div class="abs-ring"></div>' },
  { id: 'abs-pulse', title: 'Pulse', category: 'Abstract', html: '<div class="abs-pulse"><span></span><span></span></div>' },
  { id: 'abs-spiral', title: 'Spiral', category: 'Abstract', html: '<div class="abs-spiral"><span></span><span></span></div>' },
  { id: 'abs-glitch', title: 'Glitch', category: 'Abstract', html: '<div class="abs-glitch"><span></span><span></span></div>' },
  { id: 'abs-ripple', title: 'Ripple', category: 'Abstract', html: '<div class="abs-ripple"><span></span><span></span><span></span></div>' },
  { id: 'abs-kaleidoscope', title: 'Kaleidoscope', category: 'Abstract', html: '<div class="abs-kaleidoscope"><span></span></div>' },
  { id: 'abs-prism', title: 'Prism', category: 'Abstract', html: '<div class="abs-prism"><span></span><span></span></div>' },
  { id: 'abs-moebius', title: 'Moebius Strip', category: 'Abstract', html: '<div class="abs-moebius"><span></span></div>' },
  { id: 'abs-particle', title: 'Particle Field', category: 'Abstract', html: '<div class="abs-particle"><span></span></div>' }
];
